# Celebal Excellence Intern Week 1
**Basic Data Exploration and Cleaning using Pandas**

Import Library

In [106]:
import pandas as pd

In [107]:
# Load dataset
ds = pd.read_csv("/kaggle/input/datasets/anvitkumar/shopping-dataset/Combined_dataset.csv")

In [108]:
# Show first 5 rows
ds.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [109]:
# Last 5 rows
ds.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [110]:
# Shape (rows, columns)
ds.shape

(1000, 24)

In [111]:
# Column names
ds.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [112]:
# Data types
ds.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [113]:
# Summary statistics
ds.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [114]:
# Check missing values
ds.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [115]:
#Handle Missing Values
ds["discount"] = ds["discount"].fillna(0)

ds["what_customers_said"] = ds["what_customers_said"].fillna("No Review")

ds["seller_name"] = ds["seller_name"].fillna("Unknown Seller")

ds["videos"] = ds["videos"].fillna("No Video")

ds["seller_information"] = ds["seller_information"].fillna("Not Available")

ds["variations"] = ds["variations"].fillna("No Variations")

In [116]:
ds.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [117]:
#Duplicate Record Check
print("Duplicate Record : " , ds.duplicated().sum())

Duplicate Record :  0

In [118]:
print(ds["initial_price"].dtype)
print(ds["final_price"].dtype)

int64
object

In [119]:
# Show first 5 rows of initial_price and final_price
ds[["initial_price", "final_price"]].head()

   initial_price  final_price
0           3995  "₹3,995.00"
1           2899  "₹2,899.00"
2           2999  "₹2,999.00"
3           1675  "₹1,675.00"
4           2899  "₹2,899.00"

In [120]:
ds["final_price"] = pd.to_numeric(
    ds["final_price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace('"', "", regex=False),
    errors="coerce"
)

In [121]:
ds["discount_amount"] = ds["initial_price"] - ds["final_price"]

In [122]:
ds[["initial_price", "final_price", "discount_amount"]].head()

   initial_price  final_price  discount_amount
0           3995       3995.0              0.0
1           2899       2899.0              0.0
2           2999       2999.0              0.0
3           1675       1675.0              0.0
4           2899       2899.0              0.0

In [123]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                1000 non-null   float64
 7   final_price             1000 non-null   float64
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     1000 non-null   object
 16  seller_name             1000 non-null   object
 17  sizes                   1000 non-null   object
 18  videos                  1000 non-null   object
 19  seller_information      1000 non-null   object
 20  variations              1000 non-null   object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
 24  discount_amount         1000 non-null   float64
dtypes: float64(4), int64(3), object(18)
memory usage: 195.4+ KB

In [124]:
ds.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
discount_amount           0
dtype: int64

In [125]:
ds.to_csv("cleaned_dataset.csv", index=False)